name: analysis_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - matplotlib
  - numpy
  - python=3.9
  - samtools
  - bedtools
  - bwa
  - ivar>=1.3.1
  - nextalign
  - mafft
  - snakemake-minimal
